### ISSUE TITLE
Uncaught NodeError if exploration with name exists and is run again 

### ISSUE THREAD

**Issue by lu-kolb** [caglorithm/mopet#13]
## Description

If I run an exploration with a specific name and then rerun it, it fails as there exists already a node in the HD5 file.

I would have not expected this behavior, instead I expected that it would overwrite the previous run. E.g., I was changing the parameter combinations and just wanted to rerun it (iterative improvement of the experiment design).

However, there are also reasons why this might be a desired behavior, such as protecting against accidental overwrite. If so, I would propose two things: (1) handle exception and provide user friendly warning and (2) add an optional `overwrite` param to the run method that will delete existing node and save the new results.

## Minimal Example

Run the script two times. Second time will fail as HD5 node already exists.

```python
from mopet import mopet
import numpy as np

def run(params):
    return {}


params = {"a": np.arange(0, 1, 0.5)}

ex = mopet.Exploration(run, params, exploration_name="testA")
ex.run()
ex.load_results()
```

```
Traceback (most recent call last):
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/synchronization/mopet_test.py", line 11, in <module>
    ex.run()
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/mopet/mopet.py", line 129, in run
    self._pre_storage_routine()
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/mopet/mopet.py", line 328, in _pre_storage_routine
    self._init_hdf()
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/mopet/mopet.py", line 300, in _init_hdf
    self.run_group = self.h5file.create_group("/", self.exploration_name)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/tables/file.py", line 940, in create_group
    title=title, new=True, filters=filters)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/tables/group.py", line 235, in __init__
    super(Group, self).__init__(parentnode, name, _log)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/tables/node.py", line 255, in __init__
    parentnode._g_refnode(self, name, validate)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/tables/group.py", line 526, in _g_refnode
    % (self._v_pathname, childname))
tables.exceptions.NodeError: group ``/`` already has a child node named ``testA``
Closing remaining open files:exploration.h5...done
```

**Comment by lu-kolb** [comment]
The current behavior produces an unwanted side effect: the `_pre_storage_routine` method gets called after the ray jobs get started. As the ray jobs are run asynchronously, a failing of HDF storage initialization does not affect the ray jobs and they continue to run in the background. But once HDF file init failed, even if the jobs finish, results cannot be persisted.  Thus successful initialization of HDF storage should be a precondition.

Thus, I would propose to simply run the `_pre_storage_routine` before starting the ray jobs. With proper exception handling this should be sufficient. @caglorithm  what do you say?

**Comment by caglorithm** [comment]
Sorry for the late reply... I've been visiting my parents the last week. 

> I would have not expected this behavior, instead I expected that it would overwrite the previous run. E.g., I was changing the parameter combinations and just wanted to rerun it (iterative improvement of the experiment design).

It depends what we want: either we simply overwrite the exploration if it exists already, or we check whether it exists and if it does, add date/time to it. I think the second option is dirtier. The first one could lead to loss of simulated data (as you said, you just wanna change a paramter but you forgot to rename the exploration, which will cause your old results to be overwritten)...

> Thus successful initialization of HDF storage should be a precondition.

Completely true, `_pre_storage_routine`, or at least the part that checks the HDF should be done before the ray jobs are initialized! Have you catched the Exception that happens when doing so?

**Comment by lu-kolb** [comment]
No worries!

We could add an `overwrite=True|False` parameter so that the user can control the behavior. If it's set to False and exploration exists an exception will be thrown. If set to True it will overwrite the data. Per default it is set to False. This would protect against accidental loss of simulation data and the user can control the naming of the exploration so that he can easily load them again under the same name.

I have an ongoing branch 13_exception_handling where I start to catch this kind of exceptions. I will finish it in the next couple of days and move `_pre_storage_routine` before ray job scheduling.

**Comment by caglorithm** [comment]
Cool, I'm looking forward to it! I agree `overwrite` flag is a good way to go!
