### ISSUE TITLE
bool values get transformed to numpy float type

### ISSUE THREAD

**Issue by lu-kolb** [caglorithm/mopet#5]
### Description

Problem is that 0 dim arrays get always converted to float without checking the type of the given value. 

### Minimal Example:

```python
import numpy as np
from mopet import mopet

def run(params):
    return {
        "test": True,
        "test2": False
    }

ex = mopet.Exploration(run, {"a": np.arange(0, 1, 0.5)})
ex.run()
ex.load_results()

print(ex.df)
```
Output:
```
     a  test  test2
0    0   1.0    0.0
1  0.5   1.0    0.0
```

Values for test and test2 changed from bool type to numpy float type.

**Comment by caglorithm** [comment]
It would be interesting to know whether `pytables` or the hdf format in general supports boolean values. Do you know?

**Comment by lu-kolb** [comment]
I checked it yesterday for `pytables`, they have a [list of supported types](https://www.pytables.org/usersguide/datatypes.html) and bool is included.

On first look hdf does not seem to support bool format, only indirectly by transforming it to int or float, but have to look more into it.
